# Generated by Django 3.2.2 on 2021-05-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAT_PRODUCTO',
            fields=[
                ('ID_CATPROD', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de categoria producto')),
                ('NOM_CATPROD', models.CharField(max_length=50, verbose_name='Nombre de la categoria producto')),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('ID_PROD', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Id del Producto')),
                ('NOM_PROD', models.CharField(max_length=30, verbose_name='Nombre del producto')),
                ('DESC_PROD', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción del produto')),
                ('CAT_PRODUCTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postres.cat_producto')),
            ],
        ),
    ]
