# Generated by Django 3.2.3 on 2021-06-13 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAT_PRODUCTO',
            fields=[
                ('ID_CATPROD', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de la categoria')),
                ('NOM_CATPROD', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('RUT_USU', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut (sin punto ni guión)')),
                ('PASS_USU', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('NOM_USU', models.CharField(max_length=30, verbose_name='Nombre')),
                ('APE_USU', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('MAIL_USU', models.CharField(max_length=100, verbose_name='Mail')),
                ('NUMTEL_USU', models.IntegerField(verbose_name='Teléfono')),
                ('DIREC_USU', models.CharField(max_length=300, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('ID_PROD', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Id')),
                ('NOM_PROD', models.CharField(max_length=30, verbose_name='Nombre')),
                ('DESC_PROD', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('PRECIO_PROD', models.IntegerField(null=True, verbose_name='Precio')),
                ('UNIDAD_PROD', models.CharField(max_length=30, verbose_name='Unidad')),
                ('IMAGEN_PROD', models.ImageField(null=True, upload_to='', verbose_name='Imagen')),
                ('CAT_PRODUCTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postres.cat_producto', verbose_name='Categoria')),
            ],
        ),
    ]
