# Generated by Django 3.2.2 on 2021-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='PRECIO_PROD',
            field=models.IntegerField(max_length=6, null=True, verbose_name='Precio del producto'),
        ),
        migrations.AlterField(
            model_name='cat_producto',
            name='ID_CATPROD',
            field=models.IntegerField(max_length=2, primary_key=True, serialize=False, verbose_name='ID de categoria producto'),
        ),
    ]
