# Generated by Django 3.2.2 on 2021-06-10 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='IMAGEN_PROD',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='UNIDAD_PROD',
            field=models.CharField(default='c/u', max_length=30, verbose_name='Unidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='CAT_PRODUCTO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postres.cat_producto', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='DESC_PROD',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripción'),
        ),
    ]
