# Generated by Django 3.2.2 on 2021-05-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postres', '0002_alter_usuario_ape_usu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='DIREC_USU',
            field=models.CharField(max_length=300, verbose_name='Dirección'),
        ),
    ]
