# Generated by Django 3.2.3 on 2021-06-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postres', '0003_alter_usuario_direc_usu'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='IMAGEN_PROD',
            field=models.ImageField(null=True, upload_to='postres/static/postres/img', verbose_name='Imagen'),
        ),
    ]
