# Generated by Django 3.2.3 on 2021-06-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postres', '0004_producto_imagen_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_producto',
            name='ID_CATPROD',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de la categoria'),
        ),
    ]
