# Generated by Django 3.2.3 on 2021-06-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postres', '0005_alter_cat_producto_id_catprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='IMAGEN_PROD',
            field=models.ImageField(blank=True, null=True, upload_to='static/postres/img', verbose_name='Imagen'),
        ),
    ]
